- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch the latest version if application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: reload puma
    systemd:
      state: restarted
      daemon_reload: yes
      name: puma
