---
- name: Ruby and Budle installation
  hosts: all
  become: true
  tasks:
    - name: Pause for 30 sec to start apt
      pause:
        seconds: 30
    - name: installing ruby
      apt:
        name: "{{ item }}"
        state: present
      loop:
      - ruby-full
      - ruby-bundler
      - build-essential 
      - git
