- name: Configure app
  hosts: app
  become: true
  vars:
    db_host: 10.128.0.25
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Enable puma
      command: systemctl enable puma

  handlers:
  - name: reload puma
    systemd:
      state: restarted
      daemon_reload: yes
      name: puma
