---
- name: Install mongodb
  become: true
  hosts: all
  tasks:
    - name: Apt-key add
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add mongodb repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present

    - name: Upgrade packages
      apt:
        upgrade: dist


    - name: Start mongodb
      systemd:
        name: mongod
        state: started
        enabled: yes
